version: '3.9'

services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4000:4000"
    command: nodemon src/app.js --http

  discord-client:
    build:
      context: .
      dockerfile: dockerfile-discord
    volumes:
      - .:/app
      - /app/node_modules
    command: node src/discord/discordClient.js