name: Generate Glossary

on:
  push:
    paths:
      - 'phase-2/train-office/backend/csharp/app/TrainOffice/Infrastructures/DataModels/**'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Generate Glossary
      run: |
        python phase-2/train-office/backend/csharp/generate_glossary.py --data_models_dir phase-2/train-office/backend/csharp/app/TrainOffice/Infrastructures/DataModels --glossary_file phase-2/train-office/backend/csharp/glossary.md

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add phase-2/train-office/backend/csharp/glossary.md
        git commit -m "Update glossary"

    - name: create pull request
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update glossary
        title: Update glossary
        body: Update glossary
        branch: update-glossary
        base: main
        delete-branch: true
        branch-suffix: timestamp


